codec/wav: Fix golint issues. (#7)
* codec/wav: add missing article in package doc comment

* codec/wav: fix golint issues

The following were fixed.

	decoder.go:16:1: comment on exported type Decoder should be of the form "Decoder ..." (with optional leading article)
	decoder.go:45:26: error strings should not be capitalized or end with punctuation or a newline
	encoder.go:15:1: comment on exported type Encoder should be of the form "Encoder ..." (with optional leading article)
	encoder.go:110:1: comment on exported method Encoder.Close should be of the form "Close ..."
	format.go:92:26: error strings should not be capitalized or end with punctuation or a newline
	format.go:125:26: error strings should not be capitalized or end with punctuation or a newline
	format.go:128:26: error strings should not be capitalized or end with punctuation or a newline
	riff.go:123:31: error strings should not be capitalized or end with punctuation or a newline
	riff.go:130:31: error strings should not be capitalized or end with punctuation or a newline

While the following remains to be fixed; based on discussion
around the API naming.

	format.go:17:2: don't use ALL_CAPS in Go names; use CamelCase
	format.go:18:2: don't use ALL_CAPS in Go names; use CamelCase
	hdr.go:14:2: struct field SGroupId should be SGroupID

* codec/wav: simplify assertion that *Decoder implements sound.Source